### ISSUE TITLE
Change Terms to headings so they become anchors/links

### ISSUE THREAD

**Issue by vanaf1979** [FSipiano/newbieDictionary#16]
Small suggestion here:

If you change the "Terms" to headings in the markdown, Github will automatically make anchors/links for them (Hover over the page title to see the link icon appear on the left). This way people can link to a specific Term from external mediums.

I think this might be usefull!?

**Comment by FSipiano** [comment]
I'm not quite sure what you mean. Make them into links?

**Comment by FSipiano** [comment]
Great shout, done!
